export const textDetalle = {
  mantoDescription1: `Es un tallado en alabastro o Piedra de Huamanga que representa a la Virgen María con su rostro cubierto con un velo. La leyenda cuenta que Verónica, una mujer piadosa, se encontró con Jesús en su camino al Calvario y le ofreció su velo para limpiar su sudorosa y sangrante frente. Al retirar el velo, se encontró con la imagen de Jesús impresa en él. Este tallado captura ese momento, mostrando a Jesús con una expresión de compasión en su rostro. Es un tallado con un fuerte significado religioso y es muy valorado por su belleza y artesanía.`,
  mantoDescription2: `Cada Tallado está hecha a mano, por lo que su color y detalles pueden variar ligeramente de las imágenes mostradas, haciéndola única. Además, ofrecemos entregas a todas las regiones del Perú `,
  sagradaDescription1: `La Sagrada Familia es un tallado en alabastro o Piedra de Huamanga que representa a la Santa Familia, formada por Jesús, María y José. La pieza representa la unidad y amor en la familia cristiana, mostrando a Jesús, el niño Dios, en el centro rodeado de sus padres adoptivos. Es una obra de arte con un fuerte significado religioso y es valorado por su belleza y artesanía. La talla de la Sagrada Familia es una oportunidad perfecta para tener una pieza de arte religioso en tu hogar y recordar la importancia de la familia en la fe cristiana.`,
  sagradaDescription2: `Cada Tallado está hecha a mano, por lo que su color y detalles pueden variar ligeramente de las imágenes mostradas, haciéndola única. Además, ofrecemos entregas a todas las regiones del Perú`,
  chulloDescription1: `La pieza es tallado en alabastro o Piedra de Huamanga que representa el tradicional sombrero peruano llamado Chullo. El chullo es un sombrero de lana que se utiliza comúnmente en los Andes peruanos para protegerse del frío. El tallado tiene el borde dorado dando un toque especial de elegancia y riqueza. Es una obra de arte que combina la tradición y la cultura peruana con un toque moderno. Este tallado es una excelente opción para aquellos interesados en la cultura peruana y en tener una pieza única y original en su hogar u oficina.
  `,
  chulloDescription2: `
  Cada Tallado está hecha a mano, por lo que su color y detalles pueden variar ligeramente de las imágenes mostradas, haciéndola única. Además, ofrecemos entregas a todas las regiones del Perú`,
  pesebreDescription1: `El pesebre con nacimiento es un tallado en alabastro o piedra de Huamanga que representa la escena del nacimiento de Jesús en un pesebre o establo. En esta pieza se pueden ver a María, José y los reyes con el niño Jesús recién nacido, rodeados de animales y elementos típicos de un establo. Es una obra de arte con un fuerte significado religioso y es muy valorado por su artesanía. Este tallado es una excelente opción para aquellos interesados en tener una pieza con un simbolismo religioso en su hogar u oficina, especialmente durante las fiestas navideñas.
  `,
  pesebreDescription2: `Cada pieza está hecha a mano y con matices de alabastro diferentes, por lo que su color y detalles pueden variar ligeramente de las imágenes mostradas, haciéndola única. Además, ofrecemos entregas a todas las regiones del Perú`,
  pesebreNacimientoDescription1: `El pesebre con nacimiento es un tallado en alabastro o piedra de Huamanga que representa la escena del nacimiento de Jesús en un pesebre o establo. En esta pieza se pueden ver a María, José y los reyes con el niño Jesús recién nacido, rodeados de animales y elementos típicos de un establo. Es una obra de arte con un fuerte significado religioso y es muy valorado por su artesanía. Este tallado es una excelente opción para aquellos interesados en tener una pieza con un simbolismo religioso en su hogar u oficina, especialmente durante las fiestas navideñas.`,
  pesebreNacimientoDescription2: `Cada pieza está hecha a mano y con matices de alabastro diferentes, por lo que su color y detalles pueden variar ligeramente de las imágenes mostradas, haciéndola única. Además, ofrecemos entregas a todas las regiones del Perú`,
};
